[package]
name = "cli_client"
version = "0.1.0"
edition = "2024"

[dependencies]
ureq = {version = "3.0.5", features = ["json"]}
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"