#[cfg(test)]
mod test;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum Location {
	//Ireland
	Dublin,
	Rosslare,
	//UK
	Belfast,
	Cairnryan,
	Glasgow,
	Edinburgh,
	Newcastle,
	York,
	Liverpool,
	Holyhead,
	Fishguard,
	Swansea,
	Birmingham,
	Nottingham,
	Cambridge,
	Oxford,
	Plymouth,
	Bournemouth,
	London,
	//Denmark
	Aalborg,
	Aarhus,
	Esbjerg,
	Copenhagen,
	//Spain
	Bilbao,
	Burgos,
	Pamplona,
	Valladolid,
	Zaragoza,
	Madrid,
	Albacete,
	Valencia,
	Barcelona,
	//Andorra
	Andorra,
	//France
	Calais,
	LeHavre,
	Paris,
	CharlevilleMezieres,
	Brest,
	Rennes,
	Nantes,
	LeMans,
	Orleans,
	Poitiers,
	LaRochelle,
	Limoges,
	Bordeaux,
	ClermontFerrand,
	Toulouse,
	Montpellier,
	Nancy,
	Strasbourg,
	Dijon,
	Lyon,
	Grenoble,
	Marseille,
	Nice,
	//Netherlands
	Groningen,
	Amsterdam,
	TheHague,
	SHertogenbosch,
	//Belgium
	Ghent,
	Antwerp,
	Brussels,
	//Luxembourg
	Luxembourg,
	//Germany
	Kiel,
	Bremen,
	Hamburg,
	Rostock,
	Bielefeld,
	Magdeburg,
	Berlin,
	Cologne,
	Kassel,
	Erfurt,
	Leipzig,
	Dresden,
	Frankfurt,
	Nuremberg,
	Stuttgart,
	Munich,
	//Switzerland
	Basel,
	Zurich,
	Merlischachen,
	Geneva,
	//Austria
	Innsbruck,
	Salzburg,
	Linz,
	Vienna,
	Villach,
	Graz,
	//Italy
	Bolzano,
	Trento,
	Turin,
	Milan,
	Padua,
	Venice,
	Genoa,
	Bologna,
	Pisa,
	Florence,
	SanMarino,
	Perugia,
	Rome,
	//Poland
	Gdansk,
	Szczecin,
	Bydgoszcz,
	Poznan,
	Wroclaw,
	//Czech Republic
	Pilsen,
	Prague,
	Liberec,
	CeskeBudejovice,
	Brno,
	Ostrava,
	//Hungary
	Sopron,
	//Slovenia
	Ljubljana,
	//Croatia
	Rijeka,
	Zagreb,
	Split,
	//Bosnia and Herzegovina
	BanjaLuka,
}

impl Location {
	pub fn get_low_speed_connections(&self) -> Vec<Location> {
		match self {
			Location::Dublin => vec![Location::Belfast, Location::Holyhead, Location::Rosslare],
			Location::Rosslare => vec![Location::Dublin, Location::Fishguard],
			Location::Belfast => vec![Location::Dublin, Location::Cairnryan],
			Location::Cairnryan => vec![Location::Belfast, Location::Glasgow],
			Location::Glasgow => vec![Location::Cairnryan, Location::Liverpool, Location::Edinburgh],
			Location::Edinburgh => vec![Location::Glasgow, Location::Newcastle],
			Location::Newcastle => vec![Location::Edinburgh, Location::York],
			Location::York => vec![Location::Newcastle, Location::Liverpool, Location::Nottingham],
			Location::Liverpool => vec![Location::Glasgow, Location::York, Location::Birmingham, Location::Holyhead],
			Location::Holyhead => vec![Location::Dublin, Location::Liverpool],
			Location::Fishguard => vec![Location::Rosslare, Location::Swansea],
			Location::Swansea => vec![Location::Fishguard, Location::Birmingham],
			Location::Birmingham => vec![Location::Liverpool, Location::Nottingham, Location::London, Location::Oxford, Location::Swansea],
			Location::Nottingham => vec![Location::York, Location::Cambridge, Location::Birmingham],
			Location::Cambridge => vec![Location::Nottingham, Location::London],
			Location::Oxford => vec![Location::Birmingham, Location::London, Location::Bournemouth, Location::Plymouth],
			Location::Plymouth => vec![Location::Oxford, Location::Bournemouth, Location::Brest],
			Location::Bournemouth => vec![Location::Oxford, Location::London, Location::Plymouth],
			Location::London => vec![Location::Cambridge, Location::Calais, Location::Bournemouth, Location::Oxford, Location::Birmingham],
			Location::Aalborg => vec![Location::Aarhus, Location::Esbjerg],
			Location::Aarhus => vec![Location::Aalborg, Location::Copenhagen, Location::Esbjerg],
			Location::Esbjerg => vec![Location::Aalborg, Location::Aarhus, Location::Kiel],
			Location::Copenhagen => vec![Location::Aarhus, Location::Rostock, Location::Kiel],
			Location::Bilbao => vec![Location::Pamplona, Location::Burgos],
			Location::Burgos => vec![Location::Bilbao, Location::Pamplona, Location::Valladolid],
			Location::Pamplona => vec![Location::Bordeaux, Location::Zaragoza, Location::Burgos, Location::Bilbao],
			Location::Valladolid => vec![Location::Burgos, Location::Madrid],
			Location::Zaragoza => vec![Location::Pamplona, Location::Toulouse, Location::Andorra, Location::Barcelona, Location::Valencia, Location::Madrid],
			Location::Madrid => vec![Location::Valladolid, Location::Zaragoza, Location::Albacete],
			Location::Albacete => vec![Location::Madrid, Location::Valencia],
			Location::Valencia => vec![Location::Zaragoza, Location::Barcelona, Location::Albacete],
			Location::Barcelona => vec![Location::Andorra, Location::Valencia, Location::Zaragoza],
			Location::Andorra => vec![Location::Toulouse, Location::Barcelona, Location::Zaragoza],
			Location::Calais => vec![Location::London, Location::Ghent, Location::Paris],
			Location::LeHavre => vec![Location::Paris, Location::Rennes],
			Location::Paris => vec![Location::Calais, Location::Brussels, Location::CharlevilleMezieres, Location::Nancy, Location::Dijon, Location::Orleans, Location::LeMans, Location::LeHavre],
			Location::CharlevilleMezieres => vec![Location::Luxembourg, Location::Nancy, Location::Paris],
			Location::Brest => vec![Location::Plymouth, Location::Rennes, Location::Nantes],
			Location::Rennes => vec![Location::LeHavre, Location::LeMans, Location::Nantes, Location::Brest],
			Location::Nantes => vec![Location::Rennes, Location::LaRochelle, Location::Brest],
			Location::LeMans => vec![Location::Paris, Location::Poitiers, Location::Rennes],
			Location::Orleans => vec![Location::Paris, Location::Limoges, Location::Poitiers],
			Location::Poitiers => vec![Location::LeMans, Location::Orleans, Location::Limoges, Location::LaRochelle],
			Location::LaRochelle => vec![Location::Nantes, Location::Poitiers, Location::Bordeaux],
			Location::Limoges => vec![Location::Poitiers, Location::Orleans, Location::ClermontFerrand, Location::Toulouse, Location::Bordeaux],
			Location::Bordeaux => vec![Location::LaRochelle, Location::Limoges, Location::Toulouse, Location::Pamplona],
			Location::ClermontFerrand => vec![Location::Lyon, Location::Montpellier, Location::Limoges],
			Location::Toulouse => vec![Location::Limoges, Location::Montpellier, Location::Andorra, Location::Zaragoza, Location::Bordeaux],
			Location::Montpellier => vec![Location::ClermontFerrand, Location::Marseille, Location::Toulouse],
			Location::Nancy => vec![Location::Luxembourg, Location::Strasbourg, Location::Frankfurt, Location::Dijon, Location::Paris, Location::CharlevilleMezieres],
			Location::Strasbourg => vec![Location::Stuttgart, Location::Basel, Location::Nancy],
			Location::Dijon => vec![Location::Nancy, Location::Basel, Location::Lyon, Location::Paris],
			Location::Lyon => vec![Location::Dijon, Location::Geneva, Location::Grenoble, Location::ClermontFerrand],
			Location::Grenoble => vec![Location::Geneva, Location::Turin, Location::Marseille, Location::Lyon],
			Location::Marseille => vec![Location::Grenoble, Location::Nice, Location::Montpellier],
			Location::Nice => vec![Location::Genoa, Location::Marseille],
			Location::Groningen => vec![Location::Bremen, Location::Amsterdam],
			Location::Amsterdam => vec![Location::Groningen, Location::TheHague],
			Location::TheHague => vec![Location::Amsterdam, Location::Antwerp],
			Location::SHertogenbosch => vec![Location::Antwerp],
			Location::Ghent => vec![Location::Antwerp, Location::Brussels, Location::Calais],
			Location::Antwerp => vec![Location::TheHague, Location::SHertogenbosch, Location::Brussels, Location::Ghent],
			Location::Brussels => vec![Location::Antwerp, Location::Cologne, Location::Luxembourg, Location::Paris, Location::Ghent],
			Location::Luxembourg => vec![Location::Brussels, Location::Frankfurt, Location::Nancy, Location::CharlevilleMezieres],
			Location::Kiel => vec![Location::Esbjerg, Location::Copenhagen, Location::Hamburg],
			Location::Bremen => vec![Location::Groningen, Location::Hamburg, Location::Bielefeld],
			Location::Hamburg => vec![Location::Kiel, Location::Rostock, Location::Magdeburg, Location::Bremen],
			Location::Rostock => vec![Location::Copenhagen, Location::Berlin, Location::Hamburg],
			Location::Bielefeld => vec![Location::Bremen, Location::Magdeburg, Location::Kassel, Location::Cologne],
			Location::Magdeburg => vec![Location::Hamburg, Location::Berlin, Location::Erfurt, Location::Bielefeld],
			Location::Berlin => vec![Location::Rostock, Location::Szczecin, Location::Poznan, Location::Dresden, Location::Magdeburg],
			Location::Cologne => vec![Location::Bielefeld, Location::Frankfurt, Location::Brussels],
			Location::Kassel => vec![Location::Bielefeld, Location::Erfurt, Location::Frankfurt],
			Location::Erfurt => vec![Location::Magdeburg, Location::Leipzig, Location::Nuremberg, Location::Frankfurt, Location::Kassel],
			Location::Leipzig => vec![Location::Dresden, Location::Erfurt],
			Location::Dresden => vec![Location::Berlin, Location::Prague, Location::Leipzig],
			Location::Frankfurt => vec![Location::Kassel, Location::Erfurt, Location::Stuttgart, Location::Nancy, Location::Luxembourg, Location::Cologne],
			Location::Nuremberg => vec![Location::Erfurt, Location::Pilsen, Location::Munich, Location::Stuttgart],
			Location::Stuttgart => vec![Location::Frankfurt, Location::Nuremberg, Location::Munich, Location::Strasbourg],
			Location::Munich => vec![Location::Nuremberg, Location::Innsbruck, Location::Stuttgart],
			Location::Basel => vec![Location::Strasbourg, Location::Zurich, Location::Merlischachen, Location::Dijon],
			Location::Zurich => vec![Location::Innsbruck, Location::Merlischachen, Location::Basel, Location::Milan],
			Location::Merlischachen => vec![Location::Zurich, Location::Basel],
			Location::Geneva => vec![Location::Lyon, Location::Grenoble],
			Location::Innsbruck => vec![Location::Munich, Location::Salzburg, Location::Bolzano, Location::Zurich],
			Location::Salzburg => vec![Location::Linz, Location::Villach, Location::Innsbruck],
			Location::Linz => vec![Location::CeskeBudejovice, Location::Vienna, Location::Salzburg],
			Location::Vienna => vec![Location::Brno, Location::Sopron, Location::Linz],
			Location::Villach => vec![Location::Salzburg, Location::Graz, Location::Ljubljana, Location::Venice],
			Location::Graz => vec![Location::Sopron, Location::Villach],
			Location::Bolzano => vec![Location::Innsbruck, Location::Trento],
			Location::Trento => vec![Location::Bolzano, Location::Padua],
			Location::Turin => vec![Location::Milan, Location::Genoa, Location::Grenoble],
			Location::Milan => vec![Location::Zurich, Location::Padua, Location::Bologna, Location::Genoa, Location::Turin],
			Location::Padua => vec![Location::Trento, Location::Venice, Location::Bologna, Location::Milan],
			Location::Venice => vec![Location::Villach, Location::Ljubljana, Location::Padua],
			Location::Genoa => vec![Location::Milan, Location::Pisa, Location::Nice, Location::Turin],
			Location::Bologna => vec![Location::Padua, Location::SanMarino, Location::Florence, Location::Milan],
			Location::Pisa => vec![Location::Florence, Location::Rome, Location::Genoa],
			Location::Florence => vec![Location::Bologna, Location::SanMarino, Location::Perugia, Location::Pisa],
			Location::SanMarino => vec![Location::Bologna, Location::Florence],
			Location::Perugia => vec![Location::Florence, Location::Rome],
			Location::Rome => vec![Location::Perugia, Location::Pisa],
			Location::Gdansk => vec![Location::Szczecin, Location::Bydgoszcz],
			Location::Szczecin => vec![Location::Gdansk, Location::Bydgoszcz, Location::Poznan, Location::Berlin],
			Location::Bydgoszcz => vec![Location::Gdansk, Location::Poznan, Location::Szczecin],
			Location::Poznan => vec![Location::Szczecin, Location::Bydgoszcz, Location::Wroclaw, Location::Berlin],
			Location::Wroclaw => vec![Location::Poznan, Location::Ostrava, Location::Liberec],
			Location::Pilsen => vec![Location::Prague, Location::CeskeBudejovice, Location::Nuremberg],
			Location::Prague => vec![Location::Liberec, Location::Brno, Location::Pilsen, Location::Dresden],
			Location::Liberec => vec![Location::Wroclaw, Location::Prague],
			Location::CeskeBudejovice => vec![Location::Pilsen, Location::Linz],
			Location::Brno => vec![Location::Ostrava, Location::Vienna, Location::Prague],
			Location::Ostrava => vec![Location::Wroclaw, Location::Brno],
			Location::Sopron => vec![Location::Vienna, Location::Graz],
			Location::Ljubljana => vec![Location::Villach, Location::Zagreb, Location::Rijeka, Location::Venice],
			Location::Rijeka => vec![Location::Ljubljana, Location::Zagreb, Location::Split],
			Location::Zagreb => vec![Location::BanjaLuka, Location::Rijeka, Location::Ljubljana],
			Location::Split => vec![Location::BanjaLuka, Location::Rijeka],
			Location::BanjaLuka => vec![Location::Zagreb, Location::Split],
		}
	}

	fn get_iter() -> impl Iterator<Item = Location> {
		return vec![
				Location::Dublin,
				Location::Rosslare,
				Location::Belfast,
				Location::Cairnryan,
				Location::Glasgow,
				Location::Edinburgh,
				Location::Newcastle,
				Location::York,
				Location::Liverpool,
				Location::Holyhead,
				Location::Fishguard,
				Location::Swansea,
				Location::Birmingham,
				Location::Nottingham,
				Location::Cambridge,
				Location::Oxford,
				Location::Plymouth,
				Location::Bournemouth,
				Location::London,
				Location::Aalborg,
				Location::Aarhus,
				Location::Esbjerg,
				Location::Copenhagen,
				Location::Bilbao,
				Location::Burgos,
				Location::Pamplona,
				Location::Valladolid,
				Location::Zaragoza,
				Location::Madrid,
				Location::Albacete,
				Location::Valencia,
				Location::Barcelona,
				Location::Andorra,
				Location::Calais,
				Location::LeHavre,
				Location::Paris,
				Location::CharlevilleMezieres,
				Location::Brest,
				Location::Rennes,
				Location::Nantes,
				Location::LeMans,
				Location::Orleans,
				Location::Poitiers,
				Location::LaRochelle,
				Location::Limoges,
				Location::Bordeaux,
				Location::ClermontFerrand,
				Location::Toulouse,
				Location::Montpellier,
				Location::Nancy,
				Location::Strasbourg,
				Location::Dijon,
				Location::Lyon,
				Location::Grenoble,
				Location::Marseille,
				Location::Nice,
				Location::Groningen,
				Location::Amsterdam,
				Location::TheHague,
				Location::SHertogenbosch,
				Location::Ghent,
				Location::Antwerp,
				Location::Brussels,
				Location::Luxembourg,
				Location::Kiel,
				Location::Bremen,
				Location::Hamburg,
				Location::Rostock,
				Location::Bielefeld,
				Location::Magdeburg,
				Location::Berlin,
				Location::Cologne,
				Location::Kassel,
				Location::Erfurt,
				Location::Leipzig,
				Location::Dresden,
				Location::Frankfurt,
				Location::Nuremberg,
				Location::Stuttgart,
				Location::Munich,
				Location::Basel,
				Location::Zurich,
				Location::Merlischachen,
				Location::Geneva,
				Location::Innsbruck,
				Location::Salzburg,
				Location::Linz,
				Location::Vienna,
				Location::Villach,
				Location::Graz,
				Location::Bolzano,
				Location::Trento,
				Location::Turin,
				Location::Milan,
				Location::Padua,
				Location::Venice,
				Location::Genoa,
				Location::Bologna,
				Location::Pisa,
				Location::Florence,
				Location::SanMarino,
				Location::Perugia,
				Location::Rome,
				Location::Gdansk,
				Location::Szczecin,
				Location::Bydgoszcz,
				Location::Poznan,
				Location::Wroclaw,
				Location::Pilsen,
				Location::Prague,
				Location::Liberec,
				Location::CeskeBudejovice,
				Location::Brno,
				Location::Ostrava,
				Location::Sopron,
				Location::Ljubljana,
				Location::Rijeka,
				Location::Zagreb,
				Location::Split,
				Location::BanjaLuka,
		].into_iter();
	}
}