name: Build, test and push images

on:
  push

jobs:
  build_backend_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build backend image
        working-directory: backend
        env:
          IMAGE_TAG: ghcr.io/t-x-t/timetabletag-online/backend:${{ github.ref_name }}
        run: |
          docker build -t $IMAGE_TAG .
          docker save -o backend_image.tar ghcr.io/t-x-t/timetabletag-online/backend:${{ github.ref_name }}
      - name: Save docker image
        uses: actions/upload-artifact@v4
        with:
          name: backend_image
          path: backend/backend_image.tar
			
  backend_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test backend
        working-directory: backend
        run: |
          rustup toolchain install nightly --profile minimal --no-self-update
          rustup default nightly
          cargo test -j 1

  push_backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: 
      - build_backend_docker_image
      - backend_test
    steps:
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download backend image
        uses: actions/download-artifact@v4
        with:
          name: backend_image
      - name: Push backend image
        env:
          IMAGE_TAG: ghcr.io/t-x-t/timetabletag-online/backend:${{ github.ref_name }}
        run: |
          docker load -i backend_image.tar
          docker push $IMAGE_TAG